meson: explicitly set C99 standard after 57fb8074161c
GCC < 5 uses C89 by default, so the build failed with:

src/plugins/cairo/libdecor-cairo.c: In function 'ensure_cursor_theme':
src/plugins/cairo/libdecor-cairo.c:2124: error: 'for' loop initial declaration used outside C99 mode